name: Bug Report
description: Create a report to help us improve
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Your issue may have already been reported. Please check the following link for common issues and solutions.
        [Commonly faced issues and their solutions](https://github.com/KillianLucas/open-interpreter/issues/164)
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Step-by-step guide to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem.
  - type: input
    id: oiversion
    attributes:
      label: Open Interpreter Version
      description: Run `pip show open-interpreter`
      placeholder: e.g. 0.1.1
    validations:
      required: true
  - type: input
    id: pythonversion
    attributes:
      label: Python Version
      description: Run `python -V`
      placeholder: e.g. 3.11.5
    validations:
      required: true
  - type: input
    id: osversion
    attributes:
      label: OS Name and Version
      description: Provide your OS name and version.
      placeholder: e.g. Windows 11 / macOS 13 / Ubuntu 22.10
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Provide any other relevant information.